name: Build C++ EXE

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build hello.cpp
        run: |
          call "C:\Program Files\Microsoft Visual Studio\2022\Enterprise\Common7\Tools\VsDevCmd.bat" && cl /EHsc hello.cpp /Fe:hello.exe

      - name: List files for debug
        run: dir

      - name: Upload EXE as artifact
        uses: actions/upload-artifact@v4
        with:
          name: hello-artifact
          path: hello.exe
